export const Furniture = [
    {
        id: 0, 
        image: "https://workspace.com.pk/wp-content/uploads/2022/08/Sofa-Chair-1.jpg",
        title: "Office Chair",
        price: 2500,
        desc: "Upgrade your workspace with our ergonomic Office Chair, designed for ultimate comfort and productivity. Featuring adjustable lumbar support, a sleek modern design, and a 360-degree swivel, our chair ensures a tailored fit for any body type. Elevate your work experience with a stylish and supportive seating solution."
    }, 
    {
        id: 1, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSCu3gZQ9ZPmb2qHvU5qGZqH0qFDAuPOok8w&usqp=CAU",
        title: "Sofa Couch",
        price: 3099,
        desc: "Indulge in unparalleled comfort and style with our luxurious Sofa Couch. Crafted with premium materials and a contemporary design, this statement piece effortlessly transforms your living space into a haven of relaxation. Elevate your home with the perfect blend of sophistication",
    }, 
    {
        id: 2, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmfpE22fa8Y4TeHKgy1is1rXKeYQZC7yUqTg&usqp=CAU",
        title: "Wingback Chair",
        price: 1999,
        desc: "Indulge in timeless comfort and elegance with our Wingback Chair. Crafted with meticulous attention to detail, its classic design and plush upholstery create a luxurious seating experience. ",
    }, 
    {
        id: 3, 
        image: "https://m.economictimes.com/thumb/msid-99739311,width-1600,height-900,resizemode-4,imgsize-78972/fentonpremiumsofa4.jpg",
        title: "Luxurious Comfort Sofa",
        price: 9000,
        desc: "Upgrade your dining experience with our stylish Dining Chairs Set. Crafted for comfort and durability, these chairs effortlessly blend modern design with timeless elegance. Transform your dining space into a chic and inviting haven for memorable gatherings.",
    }, 
    {
        id: 4, 
        image: "https://m.media-amazon.com/images/I/51O9Tl-NarL._AC_UF894,1000_QL80_.jpg",
        title: "Dining Chairs Set",
        price: 8099,
        desc: "Elevate your dining experience with our exquisite Dining Chairs Set. Crafted with a perfect blend of style and comfort, these chairs feature a sleek design and durable construction, making them the ideal addition to your dining space. ",
    }, 
    {
        id: 5, 
        image: "https://cdn.renodepot.com/webassets/images/330741550_MainImage_001_l.jpg",
        title: "Console Table",
        price: 2099,
        desc: "Elevate your space with our sleek Console Table, a perfect blend of modern design and functionality. Crafted with premium materials, this versatile piece seamlessly complements any decor, offering a stylish surface for display and storage. ",
    }, 
    {
        id: 6, 
        image: "https://urbangalleria.com/cdn/shop/products/5_64f3bec5-e664-4693-8dc8-4be3d49360f6_1024x1024.jpg?v=1610620212",
        title: "Woodall Rocking Chair",
        price: 7600,
        desc: "Introducing the Woodall Rocking Chair a timeless blend of comfort and craftsmanship. Crafted from premium hardwood, this classic rocking chair boasts a beautifully contoured design, ensuring a relaxing and stylish addition to any space. ",
    }, 
    {
        id: 7, 
        image: "https://www.wishhub.pk/theme/image/product/3333/HL-0089_Wooden_Round_Table_With_4_Chairs_a.jpg",
        title: "Beachwood Folding Chair",
        price: 2099,
        desc: "Introducing our Beachwood Folding Chair a perfect blend of style and convenience for your outdoor adventures. Crafted with durable Beachwood, this portable chair effortlessly combines comfort with a foldable design, making it your ideal companion for beach days",
    }, 
    {
        id: 8, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlh6VqPI4z0SJltF8VZSrit5L_dNdq_iKhVA&usqp=CAU",
        title: "Dinning Table",
        price: 3599,
        desc: "Elevate your dining experience with our exquisite Dining Table, crafted with precision and style. Designed for both functionality and aesthetics, this centerpiece seamlessly blends modern elegance with timeless appeal, making every meal a delightful occasion. ",
    }, 
    {
        id: 9, 
        image: "https://foter.com/photos/424/seashell-upholstered-barrel-chair.jpeg",
        title: "Barrel Chair",
        price: 2700,
        desc: "Introducing our Barrel Chair, a perfect blend of comfort and style. Crafted with luxurious upholstery and a curved design, this chair provides unparalleled relaxation while adding a touch of sophistication to any space. Elevate your home decor with the timeless charm of our Barrel Chair.",
    }, 
    {
        id: 10, 
        image: "https://ae01.alicdn.com/kf/S3ee7dc1b6d7247dcb0881d26523a3c4bT/Modern-Minimalist-Reception-Negotiation-Table-and-Chairs-Light-Luxury-Coffee-Shop-Leisure-Dessert-Shop-Square-Desk.jpg",
        title: "Oval Dinning Table Marble Top",
        price: 3999,
        desc: "Elevate your dining space with our exquisite Oval Dining Table featuring a luxurious marble top. Crafted for both style and durability, this sophisticated centerpiece effortlessly blends modern design with timeless elegance, creating a stunning focal point for memorable gatherings. ",
    }, 
    {
        id: 11, 
        image: "https://ae01.alicdn.com/kf/Sc89fd17170a446608041e1826c4591faJ/Wood-Porch-Rocking-Chair-White-Color-Weather-Resistant-Finish-Garden-Chair-Outdoor-Furniture-Patio-Furniture-Modern.jpg",
        title: "Wooden Rocking Chair Set",
        price: 6999,
        desc: "Elevate your relaxation with our Wooden Rocking Chair Set, crafted for timeless comfort and style. Immerse yourself in the soothing rhythm of gentle rocking on these sturdy, beautifully designed chairs, perfect for any indoor or outdoor space. ",
    }, 
    {
        id: 12, 
        image: "https://www.paktameer.com/uploads/product-images/c0e0b07653a5db7d7c65fa0d0e0bb875_500.jpg",
        title: "Coffee Table",
        price: 2599,
        desc: "Elevate your living space with our sleek and contemporary Coffee Table. Crafted with precision and style in mind, this functional centerpiece seamlessly blends form and function. Experience the perfect balance of sophistication and practicality for your home.",
    }, 
    {
        id: 13, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqZLWvyvfTZf7I-B48klLxC9hegV2pkFdMCA&usqp=CAU",
        title: "Dowinx Gaming Chair",
        price: 5999,
        desc: "Experience the pinnacle of comfort and style with the Dowinx Gaming Chair. Engineered for gamers, this ergonomic marvel offers unparalleled support with its adjustable features, ensuring immersive gaming sessions. Elevate your gaming setup with the Dowinx Gaming Chair",
    }, 
    {
        id: 14, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9vYFozj_Mh6YJ2UvYerpM_Q6HCjg55mLcsA&usqp=CAU",
        title: "Black Wardrobes",
        price: 2599,
        desc: "Elevate your bedroom aesthetics with our sleek and sophisticated Black Wardrobes. Designed for both style and functionality, these spacious wardrobes provide ample storage while adding a touch of modern elegance to your space. Organize your clothing in style with this versatile and timeless furniture piece.",
    }, 
    {
        id: 15, 
        image: "https://multiwood.com.pk/cdn/shop/products/712lQ-Zo9EL._AC_SL1500_1024x1024@2x.jpg?v=1674591397",
        title: "Mesh office chair Chair",
        price: 4099,
        desc: "Experience unparalleled comfort and support with our Mesh Office Chair. Designed for long hours of productivity, this sleek and breathable chair features a contoured mesh back, adjustable lumbar support, and a sturdy ergonomic design, making it the perfect addition to any modern workspace.",
    }, 
    {
        id: 16, 
        image: "https://www.furnituremaxi.com/cdn/shop/products/593A7530.jpg?v=1662632318",
        title: "Gray Wooden Wardrobe",
        price: 4099,
        desc: "Introducing our Gray Wooden Wardrobe, a perfect blend of style and functionality for your living space. Crafted with high-quality wood, its sleek gray finish adds a touch of sophistication to any room. With ample storage space and a timeless design, this wardrobe seamlessly combines practicality and aesthetic appeal",
    }, 
    {
        id: 17, 
        image: "https://dpi399zi9oi5i.cloudfront.net/wp-content/uploads/2022/10/1-58.jpeg",
        title: "Study Desk with Bookshelf Storage",
        price: 4099,
        desc: "versatile and stylish solution for productive study sessions. Organize your essentials with ease, thanks to the integrated bookshelf, while the spacious desk provides a dedicated workspace. Crafted for both functionality and aesthetics, this desk is perfect for students and professionals alike, offering a blend of practicality and contemporary design to elevate your work or study environment.",
    }, 
];
export const Accessories = [
    {
        id: 0, 
        image: "https://image.made-in-china.com/2f0j00dNsiSoGcMaqk/Nordic-Table-Living-Room-Metal-Abstract-Gold-Home-Decor-Gold-Accessories-for-Home.jpg",
        title: "Metal Gold Home Decor",
        price: 2500,
        desc: "Elevate your living space with our exquisite Metal Gold Home Decor collection. Crafted with precision and sophistication, each piece seamlessly blends modern design with timeless elegance, adding a touch of opulence to your home. ",
    }, 
    {
        id: 1, 
        image: "https://static-01.daraz.pk/p/dd2ce014b0c194deafbfbfa16626c7c4.jpg_750x750.jpg_.webp",
        title: "Velvet Pleated Cushions",
        price: 3099,
        desc: "Indulge in luxurious comfort with our Velvet Pleated Cushions, designed to elevate your home decor effortlessly. Crafted from sumptuous velvet fabric and featuring exquisite pleats, these cushions add a touch of sophistication and softness to any space.",
    }, 
    {
        id: 2, 
        image: "https://www.bareezehome.com.pk/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/f/c/fch-414a_b.jpg",
        title: "Linen Cushions",
        price: 1999,
        desc: "Elevate your home decor with our exquisite Linen Cushions, crafted from premium quality linen fabric for a perfect blend of comfort and style. Immerse yourself in the softness of natural fibers while adding a touch of sophistication to any space. ",
    }, 
    {
        id: 3, 
        image: "https://pth-homes.com/cdn/shop/collections/Shopify_category_banner_6.png?v=1686121710",
        title: "Throws Blankets",
        price: 9000,
        desc: "Wrap yourself in warmth and style with our luxurious Throws Blankets. Crafted from premium materials, these cozy companions are perfect for chilly nights or adding a touch of elegance to your home decor. Elevate your comfort with our exquisite collection of Throws Blankets.",
    }, 
    {
        id: 4, 
        image: "https://m.media-amazon.com/images/I/71gGWwelIUL.jpg",
        title: "Geometric Print Rug",
        price: 8099,
        desc: "Elevate your space with our Geometric Print Rug, a chic and modern addition to any room. Crafted with precision, its bold patterns and vibrant colors create a stylish focal point, seamlessly blending contemporary design with comfort underfoot.",
    }, 
    {
        id: 5, 
        image: "https://m.media-amazon.com/images/I/71vjKrHlTdL.jpg",
        title: "Throws Blankets",
        price: 2099,
        desc: "Indulge in coziness with our luxurious Throws Blankets – crafted from premium materials for unparalleled warmth and comfort. Elevate your home decor with a stylish range of colors and patterns, perfect for snuggling up on chilly evenings. ",
    }, 
    {
        id: 6, 
        image: "https://www.cotswoldco.com/_next/image/?url=https%3A%2F%2Fcotswoldco-cdn.azureedge.net%2Fproducts%2F926.271_lx59niyi.6.jpg&w=3840&q=75",
        title: "Grass Printed Cushions",
        price: 7600,
        desc: "Elevate your home decor with our Grass Printed Cushions, bringing the soothing essence of nature indoors. Crafted from high-quality materials, these cushions seamlessly blend comfort with style, creating a refreshing and contemporary ambiance for your living space.",
    }, 
    {
        id: 7, 
        image: "https://m.media-amazon.com/images/I/71QVSQHPVxL._AC_UF894,1000_QL80_.jpg",
        title: "Gray White Carpet",
        price: 2099,
        desc: "Elevate your space with our Gray White Carpet, a perfect blend of sophistication and versatility. Crafted with high-quality materials, its neutral tones seamlessly complement any décor, creating a timeless and cozy ambiance for your home or office. ",
    }, 
    {
        id: 8, 
        image: "https://m.media-amazon.com/images/I/71ZAqvK2LNL.jpg",
        title: "Pink Square Box Rug",
        price: 3599,
        desc: "Elevate your space with our Pink Square Box Rug, a chic and contemporary addition to any room. Crafted with quality materials, its soft texture and vibrant hue bring both comfort and style to your home. Transform your living space with this eye-catching and versatile rug",
    }, 
    {
        id: 9, 
        image: "https://foter.com/photos/424/seashell-upholstered-barrel-chair.jpeg",
        title: "Barrel Chair",
        price: 2700,
        desc: "Introducing our Barrel Chair, a perfect blend of style and comfort. Crafted with precision, its curved design offers a cozy embrace, while the premium upholstery ensures a touch of luxury. Elevate your space with this statement piece that seamlessly combines modern aesthetics with relaxation.",
    }, 
    {
        id: 10, 
        image: "https://img.fruugo.com/product/7/15/953794157_max.jpg",
        title: "Round Rug",
        price: 3999,
        desc: "Elevate your space with our Round Rug a perfect blend of style and comfort. Crafted with premium materials, this chic accessory adds a touch of sophistication to any room, creating a cozy and inviting atmosphere. Transform your home decor effortlessly ",
    }, 
    {
        id: 11, 
        image: "https://static.wixstatic.com/media/d5f376_5d545e8365914ad8bd7f2912ac4ff7df~mv2.jpg/v1/fill/w_640,h_640,al_c,lg_1,q_85,enc_auto/d5f376_5d545e8365914ad8bd7f2912ac4ff7df~mv2.jpg",
        title: "Round Mirror",
        price: 6999,
        desc: "Elevate your space with our exquisite Round Mirror, a perfect blend of timeless design and modern elegance. Crafted with precision, its sleek metal frame encases a crystal-clear reflection, adding a touch of sophistication to any room. ",
    }, 
    {
        id: 12, 
        image: "https://static-01.daraz.pk/p/442923b59c3ecfc24ca3c68c1dd54bd6.png",
        title: "Tree Wall Art",
        price: 2599,
        desc: "Elevate your space with our stunning Tree Wall Art, a captivating fusion of nature and craftsmanship. Crafted with precision, these exquisite pieces bring the outdoors inside, adding a touch of organic beauty to your home decor. ",
    }, 
    {
        id: 13, 
        image: "https://m.media-amazon.com/images/I/71sy769wYIL._AC_UF894,1000_QL80_.jpg",
        title: "Metal Wall Clock",
        price: 5999,
        desc: "Elevate your home decor with our sleek Metal Wall Clock. Combining modern design with timeless functionality, this stylish timepiece effortlessly adds a touch of sophistication to any room. Crafted with precision and durability, our metal wall clock is a statement piece that stands the test of time.",
    }, 
    {
        id: 14, 
        image: "https://myhomestore.pk/cdn/shop/products/il_1140xN.3646795440_nlyr_jpg.jpg?v=1672131560",
        title: "Gold Metal Wall Decor",
        price: 2599,
        desc: "Elevate your space with our exquisite Gold Metal Wall Decor, a statement piece that seamlessly blends elegance and modern design. Crafted with precision, this eye-catching accent adds a touch of glamour to any room, creating a sophisticated atmosphere ",
    }, 
    {
        id: 15, 
        image: "https://esentiments.pk/wp-content/uploads/2023/04/WhatsApp-Image-2023-04-08-at-14.50.30.jpg",
        title: "3-Piece Wall Mirror Set",
        price: 4099,
        desc: "Elevate your space with our 3-Piece Wall Mirror Set, a stylish ensemble designed to enhance any room's aesthetic. Crafted with sleek frames and varying sizes, these mirrors add depth and sophistication to your walls, creating a stunning visual focal point for your home or office",
    }, 
];
export const Kitchen = [
    {
        id: 0, 
        image: "https://www.arzaan.pk/cdn/shop/files/133701771088784889_1024x1024.jpg?v=1689891825",
        title: "Stainless Steel Cutlery Set",
        price: 2500,
        desc: "Elevate your dining experience with our exquisite Stainless Steel Cutlery Set, meticulously crafted for durability and elegance. This sleek and modern set is designed to enhance your table aesthetics while providing a comfortable grip for a delightful dining journey. ",
    }, 
    {
        id: 1, 
        image: "https://m.economictimes.com/thumb/height-450,width-600,imgsize-680566,msid-100192211/6-best-crockery-dinner-sets-to-impress-your-guests.jpg",
        title: "Crockery Dinner Set",
        price: 3099,
        desc: "Elevate your dining experience with our exquisite Crockery Dinner Set. Crafted with precision and elegance, this stylish yet durable collection adds a touch of sophistication to your table. Perfect for everyday meals or special occasions, our dinner set seamlessly combines functionality and aesthetics.",
    }, 
    {
        id: 2, 
        image: "https://www.nestroots.com/cdn/shop/products/nestroots-wooden-serving-bowls-snacks-sweet-bowl-rice-bowl-salad-bowl-soup-dip-bowl-set-combo-enamel-printed-colorfull-bowls-for-dining-table-and-kitchen-4_724fd783-ae09-47c1-bd9f-0d129f2f6004.jpg?v=1651234369",
        title: "Wooden Bowls",
        price: 1999,
        desc: "Elevate your dining experience with our exquisite Wooden Bowls, crafted from premium, sustainable wood. Each bowl is a harmonious blend of timeless design and functional artistry, bringing a touch of nature to your table.",
    }, 
    {
        id: 3, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTioEFbV-OQ_7hhLEQvynH_guozpfvnh7d77g&usqp=CAU",
        title: "Dining Chair",
        price: 9000,
        desc: "Elevate your dining experience with our stylish Dining Chairs Set. Crafted for comfort and sophistication, these chairs seamlessly blend modern design with durability, making them the perfect addition to your dining space. Enjoy quality and aesthetics in every meal with this chic and practical seating solution",
    }, 
    {
        id: 4, 
        image: "https://m.media-amazon.com/images/I/51O9Tl-NarL._AC_UF894,1000_QL80_.jpg",
        title: "Dining Chairs Set",
        price: 8099,
        desc: "Elevate your dining experience with our stylish Dining Chairs Set. Crafted for comfort and sophistication, these chairs seamlessly blend modern design with durability, making them the perfect addition to your dining space. Enjoy quality and aesthetics in every meal with this chic and practical seating solution",
    }, 
    {
        id: 5, 
        image: "https://images.woodenstreet.de/image/cache/data%2Fhomeware%2Ftableware%2Fcutlery%2Fcutlery-holder-with-black-finish-handle-3-section-spoon-stand%2F1-750x650.jpg",
        title: "Cutlery Stand",
        price: 2099,
        desc: "Elevate your kitchen organization with our sleek Cutlery Stand, a stylish and space-saving solution for neatly storing knives and utensils. Crafted from durable materials, this compact stand adds a touch of elegance to your countertop while keeping your cutlery easily accessible. ",
    }, 
    {
        id: 6, 
        image: "https://cdn.shopify.com/s/files/1/2690/0106/files/DSC_8564_480x480.jpg?v=1621666980",
        title: "White Dinner Set",
        price: 7600,
        desc: "Elevate your dining experience with our White Dinner Set, a timeless collection that effortlessly blends sophistication with versatility. Crafted from high-quality porcelain, each piece showcases a pristine white finish, adding a touch of elegance to any table setting. ",
    }, 
    {
        id: 7, 
        image: "https://m.media-amazon.com/images/I/61FA8QXhJSL._AC_UF1000,1000_QL80_.jpg",
        title: "Soup Serving Bowls",
        price: 2099,
        desc: "Elevate your dining experience with our stylish Soup Serving Bowls. Crafted for both practicality and elegance, these bowls feature a generous capacity, ergonomic design, and versatile aesthetics to enhance the presentation of your favorite soups. ",
    }, 
    {
        id: 8, 
        image: "https://assets.weimgs.com/weimgs/rk/images/wcm/products/202343/0103/anillo-handcrafted-ceramic-mug-q.jpg",
        title: "Ceramic Cups",
        price: 3599,
        desc: "Elevate your beverage experience with our exquisite Ceramic Cups. Crafted with precision and style, these cups not only showcase a timeless design but also ensure a perfect sipping experience. Enhance your daily ritual with the sophistication of our durable and aesthetically pleasing ceramic cups.",
    }, 
    {
        id: 9, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSugTXuljVMyXOBqLBA_afNkHvQvSqpRjNnCg&usqp=CAU",
        title: "Wooden Spoon",
        price: 2700,
        desc: "Elevate your culinary experience with our premium Wooden Spoon crafted from high-quality, sustainable wood. Designed for precision and durability, our artisanal spoons bring a touch of natural elegance to your kitchen, making every cooking moment a pleasure.",
    }, 
    {
        id: 10, 
        image: "https://s.yimg.com/ny/api/res/1.2/CrWSMLAY_bTFECVc1vVOog--/YXBwaWQ9aGlnaGxhbmRlcjtoPTY2Ng--/https://media.zenfs.com/en/in_the_know_500/22941142db79f3a0189b39696a8881eb",
        title: "White Dinner Set",
        price: 3999,
        desc: "Elevate your dining experience with our exquisite White Dinner Set. Crafted with premium porcelain, this timeless collection combines contemporary elegance with durability, bringing a touch of sophistication to every meal. Create lasting memories with this versatile and stylish addition to your table.",
    }, 
    {
        id: 11, 
        image: "https://assets.wfcdn.com/im/66092186/resize-h310-w310%5Ecompr-r85/1554/155436058/kakig-16-piece-dinnerware-set-service-for-4.jpg",
        title: "Cottage Dinner Set",
        price: 6999,
        desc: "Elevate your dining experience with our Cottage Dinner Set, a charming ensemble that blends rustic charm with modern elegance. Crafted with care, this timeless dinnerware collection effortlessly transforms any meal i",
    }, 
    {
        id: 12, 
        image: "https://kitchenbazar.pk/wp-content/uploads/2020/12/IMG_20201201_120118.jpg",
        title: "Wooden Spoon Set",
        price: 2599,
        desc: "Elevate your culinary experience with our Wooden Spoon Set, crafted from high-quality, sustainable hardwood. These stylish and ergonomic spoons are perfect for stirring, mixing, and serving, adding a touch of natural elegance to your kitchen.",
    }, 
    {
        id: 13, 
        image: "https://images.meesho.com/images/products/267535820/gk5eq_512.webp",
        title: "Wooden Cutlery Holder",
        price: 5999,
        desc: "Elevate your kitchen organization with our Wooden Cutlery Holder, a stylish and eco-friendly solution to keep your utensils in order. Crafted from high-quality wood, this compact holder adds a touch of rustic charm to your countertop while efficiently organizing your cutlery collection. ",
    }, 
    {
        id: 14, 
        image: "https://5.imimg.com/data5/SELLER/Default/2023/2/CI/DB/RV/85707207/wooden-cutlery-tray-500x500.jpg",
        title: "Wooden Cutlery Set",
        price: 2599,
        desc: "Elevate your dining experience with our eco-friendly Wooden Cutlery Set. Crafted from sustainable, biodegradable materials, this stylish and durable set is perfect for conscious consumers who appreciate the beauty of nature in every meal. ",
    }, 
    {
        id: 15, 
        image: "https://cdn.media.amplience.net/s/hobbylobby/5994264-81162406-11272023-IMGSET?fmt=webp&w=544&h=544&sm=mc",
        title: "Spinwash Dinnerware",
        price: 4099,
        desc: "Introducing Spinwash Dinnerware the innovative solution for effortlessly clean and spotless dishes. Our cutting-edge technology combines powerful spinning action with water jets, ensuring a thorough and efficient wash every time. Elevate your dining experience with the ultimate in convenience and hygiene.",
    }, 
];
export const HomeOffice = [
    {
        id: 0, 
        image: "https://interwood.pk/cdn/shop/products/fg050000478.jpg?v=1699177297",
        title: "Staff Chair",
        price: 2500,
        desc: "Elevate your workspace with our ergonomic Staff Chair, designed for ultimate comfort and support during long hours. Featuring adjustable height and a sleek, modern design, this chair seamlessly blends style with functionality. Enhance productivity and well-being for your team with our premium Staff Chair.",
    }, 
    {
        id: 1, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9Z9n02T5XjpDsilSw-nB4wIhKrXwdHP7dkw&usqp=CAU",
        title: "Wood Book Shelf",
        price: 3099,
        desc: "Introducing our exquisite Wood Bookshelf – a timeless blend of functionality and elegance. Crafted from premium hardwood, this sturdy and stylish piece seamlessly complements any decor while providing ample storage for your favorite reads. ",
    }, 
    {
        id: 2, 
        image: "https://m.media-amazon.com/images/I/618pcUGljmS._AC_UF1000,1000_QL80_.jpg",
        title: "Plant Pots",
        price: 1999,
        desc: "Elevate your green space with our stylish Plant Pots, crafted to seamlessly blend functionality and aesthetics. Designed for both indoor and outdoor use, our durable pots provide the perfect home for your beloved plants, adding a touch of elegance to any environment. ",
    }, 
    {
        id: 3, 
        image: "https://static-01.daraz.pk/p/b27e3b18ff5f597db28d7c02363b065a.jpg_750x750.jpg_.webp",
        title: "Wooden Table Workspace",
        price: 9000,
        desc: "Introducing our Wooden Table Workspace – a harmonious blend of functionality and elegance. Crafted with precision from premium wood, this workspace seamlessly integrates into your home or office, providing a sophisticated and inspiring environment for work or creativity.",
    }, 
    {
        id: 4, 
        image: "https://images-cdn.ubuy.co.in/64cc05800973ef2610098a40-hbada-office-chair-desk-chair-with-flip.jpg",
        title: "Office Comfortable Chair",
        price: 8099,
        desc: "Upgrade your office experience with our Office Comfortable Chair, meticulously designed for optimal support and comfort. With ergonomic features and premium materials, this chair effortlessly combines style and functionality, ensuring a productive and enjoyable work environment. ",
    }, 
    {
        id: 5, 
        image: "https://image.made-in-china.com/202f0j00PmAVpwaRfdzL/Simple-Home-Office-School-Modern-5-Layers-Corner-Bookshelves-Wall-Shelves-for-Bedroom-Living-Room.webp",
        title: "5 Layers Corner Shelf",
        price: 2099,
        desc: "Maximize your space with our 5 Layers Corner Shelf! This versatile and sturdy shelving unit is designed to fit seamlessly into any corner, providing ample storage for books, decor, or essentials. Organize in style and make the most of every corner in your home or office.",
    }, 
    {
        id: 6, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSMgslG24ibmX8Mwedt2SMAmPEX19v-YIhRMnImuuWWJHqoebbgXTmvXO0EmE1bSELado&usqp=CAU",
        title: "Wall Folding Table",
        price: 7600,
        desc: "Introducing our Wall Folding Table the perfect space-saving solution for any room! Crafted with durability and style in mind, this sleek and versatile table effortlessly folds against the wall when not in use, maximizing your space without compromising on functionality. ",
    }, 
    {
        id: 7, 
        image: "https://m.media-amazon.com/images/I/61YFzRQWUJL.jpg",
        title: "Simple Procelian Planter",
        price: 2099,
        desc: "Elevate your greenery with our Simple Porcelain Planter, a minimalist masterpiece designed to complement any space. Crafted with high-quality porcelain, this sleek and versatile planter effortlessly combines timeless elegance with functionality, making it the perfect home for your favorite plants",
    }, 
    {
        id: 8, 
        image: "https://www.refinery29.com/images/10228428.png",
        title: "White Comfortable Office Chair",
        price: 3599,
        desc: "Experience unparalleled comfort and style with our White Comfortable Office Chair. Designed for extended hours of productivity, this ergonomic chair combines sleek aesthetics with plush cushioning to provide optimal support, making it the perfect addition to your workspace.",
    }, 
    {
        id: 9, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiJRhgalQqZQVOpcp8EbaXrxlwZiT8OtAxrQ&usqp=CAU",
        title: "Desktop Book Shelf Office",
        price: 2700,
        desc: "Transform your workspace with our Desktop Bookshelf Office – a sleek and functional solution for organizing your books, documents, and office essentials. Elevate your productivity with this stylish desktop accessory, designed to keep everything within arm's reach while adding a touch of sophistication ",
    }, 
    {
        id: 10, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-jw7HzRBRGXNXEd2MHq054fDQIHCAzvsYUQ&usqp=CAU",
        title: "Computer Table",
        price: 3999,
        desc: "Elevate your workspace with our sleek and sturdy Computer Table, designed for optimal functionality and style. Crafted with premium materials, this modern desk features ample surface area, cable management solutions, and ergonomic design to enhance your productivity and comfort.",
    }, 
    {
        id: 11, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3A3Xpen3sc0ZxFAjSdV_Xpw23SaxxMOpr7w&usqp=CAU",
        title: "Wooden Office Table and Chair",
        price: 6999,
        desc: "Elevate your workspace with our exquisite Wooden Office Table and Chair set, crafted for both functionality and style. Impeccably designed, this durable duo seamlessly blends natural beauty with modern efficiency, creating an inspiring environment for productive workdays.",
    }, 
    {
        id: 12, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy8eaK5CRIH-wRGSyxFeLofzyyB8bqGLonmQ&usqp=CAU",
        title: "Bambo BookShelf",
        price: 2599,
        desc: "Introducing the Bambo BookShelf – a sleek and eco-friendly storage solution for your literary treasures. Crafted from sustainable bamboo, this minimalist bookshelf seamlessly blends style and functionality, providing a modern touch to your home while promoting environmental consciousness.",
    }, 
    {
        id: 13, 
        image: "https://i.pinimg.com/736x/c3/a3/d0/c3a3d05c53d35b66c5e88f1293086339.jpg",
        title: "Office Table",
        price: 5999,
        desc: "Elevate your workspace with our sleek and functional Office Table, designed for optimum productivity and comfort. Crafted with premium materials and a contemporary aesthetic, this table seamlessly blends style with practicality, making it the perfect centerpiece for your professional environment.",
    }, 
    {
        id: 14, 
        image: "https://cdn1.bigcommerce.com/server600/eqcqd/products/34910/images/899011/BT-698-GY-GG_LS__61541.1657221582.1280.1280.jpg?c=2",
        title: "Low Back Gray Office Chair",
        price: 2599,
        desc: "Elevate your workspace with our Low Back Gray Office Chair, a sleek and stylish addition designed for comfort and productivity. Featuring a modern gray finish and ergonomic support, this chair effortlessly blends functionality with contemporary aesthetics",
    }, 
    {
        id: 15, 
        image: "https://m.media-amazon.com/images/I/71+Swcf1-4L._AC_UF1000,1000_QL80_DpWeblab_.jpg",
        title: "Corner 3 Layers Wooden BookShelf",
        price: 4099,
        desc: "Elevate your space with our Corner 3 Layers Wooden Bookshelf, a stylish and functional solution for maximizing your room's storage capacity. Crafted from premium wood, this space-saving shelving unit seamlessly fits into corners, providing an elegant display for your favorite books and decor items.",
    }, 
];

export const Outdoor = [
    {
        id: 0, 
        image: "https://urbangalleria.com/cdn/shop/products/5_64f3bec5-e664-4693-8dc8-4be3d49360f6_1024x1024.jpg?v=1610620212",
        title: "Woodall Roacking Chair",
        price: 7600,
        desc: "Introducing the Woodall Rocking Chair, a timeless blend of comfort and craftsmanship. Crafted from premium wood, its classic design and sturdy construction ensure a relaxing and durable seating experience. Elevate your space with this elegant rocking chair, where style meets serenity.",
    }, 
    {
        id: 1, 
        image: "https://www.bassettfurniture.com/dw/image/v2/BGNC_PRD/on/demandware.static/-/Sites-bassett-Library/default/dwb257a109/outdoor/CLP_outdoor_tabbedcar_hunt.jpg",
        title: "Patio Chair Set",
        price: 3099,
        desc: "Elevate your outdoor living with our stylish Patio Chair Set. Crafted for comfort and durability, this set features sleek designs, weather-resistant materials, and a perfect blend of functionality and elegance. ",
    }, 
    {
        id: 2, 
        image: "https://www.wishhub.pk/theme/image/product/3333/HL-0089_Wooden_Round_Table_With_4_Chairs_a.jpg",
        title: "Beachwood Folding Chair",
        price: 2099,
        desc: "Introducing our Beachwood Folding Chair – a perfect blend of elegance and functionality for your seaside adventures. Crafted from durable beachwood, this portable chair offers comfort and style, ensuring relaxation wherever the tide takes you. Embrace the beach life with convenience and charm.",
    }, 
    {
        id: 3, 
        image: "https://www.ubuy.com.pk/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvODEwb2x2YVFGMUwuX0FDX1NMMTUwMF8uanBn.jpg",
        title: "Swing Chair",
        price: 9000,
        desc: "Experience ultimate relaxation with our Swing Chair – a stylish and comfortable addition to any space. Crafted with quality materials, its sturdy design and soothing swinging motion create a perfect retreat for lounging indoors or outdoors. ",
    }, 
    {
        id: 4, 
        image: "https://m.media-amazon.com/images/I/61YFzRQWUJL.jpg",
        title: "Simple Procelian Planter",
        price: 2099,
        desc: "Elevate your greenery with our Simple Porcelain Planter – a minimalist and timeless addition to any space. Crafted with precision, its clean lines and smooth finish bring a touch of sophistication to your plants, making it the perfect accent for both modern and classic interiors.",
    }, 
    {
        id: 5, 
        image: "https://i.ebayimg.com/images/g/fKsAAOSwCYlf9cMK/s-l1600.jpg",
        title: "Red Basket Swing",
        price: 2099,
        desc: "Elevate your outdoor experience with our Red Basket Swing – a stylish and comfortable addition to any backyard. Crafted with durable materials, this vibrant swing not only adds a pop of color but also provides a cozy retreat for relaxation and leisure. ",
    }, 
    {
        id: 6, 
        image: "https://cdn-tp3.mozu.com/24645-m1/cms/files/12072-sectionOutdoorFurniture_diningSets.jpg",
        title: "Metal and Wood Patio Furniture",
        price: 7600,
        desc: "Elevate your outdoor space with our exquisite Metal and Wood Patio Furniture collection. Crafted with precision and style in mind, each piece seamlessly blends durable metal frames with rich wood accents, creating a perfect harmony of modern design and natural warmth. ",
    }, 
    {
        id: 7, 
        image: "https://image.made-in-china.com/44f3j00ToPhDRvwnMqC/Modern-Style-Outdoor-Hanging-Chair-Patio-Garden-Swing-Chairs-for-Sale.webp",
        title: "Outdoor Hanging Chair",
        price: 2099,
        desc: "Experience ultimate relaxation in our Outdoor Hanging Chair, crafted for stylish comfort and leisure. Suspend yourself in the embrace of durable, weather-resistant materials, creating the perfect oasis for lounging in your garden or on your patio. Elevate your outdoor living space with this modern and inviting addition.",
    }, 
    {
        id: 8, 
        image: "https://ae01.alicdn.com/kf/Sc89fd17170a446608041e1826c4591faJ/Wood-Porch-Rocking-Chair-White-Color-Weather-Resistant-Finish-Garden-Chair-Outdoor-Furniture-Patio-Furniture-Modern.jpg",
        title: "Wooden Rocking Chair Set",
        price: 6999,
        desc: "Experience timeless comfort and classic charm with our Wooden Rocking Chair Set. Crafted with precision from quality wood, this set seamlessly blends rustic elegance with modern durability, providing the perfect addition to your home for relaxation and style.",
    }, 
    {
        id: 9, 
        image: "https://image.made-in-china.com/44f3j00olCVihLqCIkP/Metal-Hanging-Chairs-for-Sale-Double-Swing-Chair-with-Stand.webp",
        title: "Hanging Chair",
        price: 2700,
        desc: "Experience ultimate relaxation with our Hanging Chair, a stylish and comfortable addition to any space. Crafted with durable materials and a chic design, this suspended seat offers a cozy retreat, perfect for lounging indoors or creating a cozy corner in your outdoor oasis. Elevate your comfort and style with our Hanging Chair",
    }, 
    {
        id: 10, 
        image: "https://www.southernliving.com/thmb/KLVsQHvZQ4q6aP_xDVWGS4Hawlk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/best-choice-products-48in-wood-porch-swing-tout-fff58a18636f404b9a687a96e60fd739.jpg",
        title: "Porch Wooden Swing",
        price: 3999,
        desc: "Transform your porch into a cozy haven with our Porch Wooden Swing. Crafted with exquisite precision and durable hardwood, this charming swing offers a perfect blend of comfort and style, inviting you to unwind and enjoy leisurely moments in the serenity of your outdoor space.",
    }, 
    {
        id: 11, 
        image: "https://m.media-amazon.com/images/I/618pcUGljmS._AC_UF1000,1000_QL80_.jpg",
        title: "Plant Pots",
        price: 1999,
        desc: "Elevate your green space with our stylish Plant Pots – crafted for both beauty and functionality. Choose from a range of premium materials and contemporary designs to showcase your favorite plants in a chic and modern way. Transform any corner of your home into a flourishing oasis with our versatile",
    }, 
    {
        id: 12, 
        image: "https://www.wfla.com/wp-content/uploads/sites/71/2023/06/better-homes-and-gardens-patio-furniture-is-super-chic-and-its-on-sale-1.jpg?w=1280",
        title: "Outdoor cushions",
        price: 2599,
        desc: "Elevate your outdoor comfort with our premium Outdoor Cushions. Crafted for durability and style, these weather-resistant cushions bring a touch of luxury to your patio or garden furniture. Experience relaxation in every moment with our exquisite outdoor cushion collection.",
    }, 
    {
        id: 13, 
        image: "https://ak1.ostkcdn.com/images/products/is/images/direct/12e9b6ccf4ae85692ee170b439c5a2aec7367f10/Sunbrella-Tan-Leopard-Indoor-Outdoor-Cushion-Set%2C-Corded.jpg?impolicy=medium",
        title: "Outdoor Corded Chair",
        price: 5999,
        desc: "Elevate your outdoor relaxation with our Outdoor Corded Chair, designed for both comfort and durability. Crafted with weather-resistant materials, this stylish chair seamlessly blends into any outdoor setting, providing a perfect spot to unwind and enjoy the great outdoors. ",
    }, 
    {
        id: 14, 
        image: "https://www.urbanplant.in/cdn/shop/files/Primary1copy_b778ed81-f3e1-449d-b723-8a52a4ac7b0d.webp?v=1685116236",
        title: "Hanging Planter",
        price: 2599,
        desc: "Elevate your green space with our Hanging Planter – a stylish and space-saving solution for bringing nature indoors. Crafted with durable materials and a sleek design, this versatile planter adds a touch of modern elegance to any room, while effortlessly showcasing your favorite plants in suspended beauty.",
    }, 
    {
        id: 15, 
        image: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/81pYUWgPZDL.jpg",
        title: "Hanging Flower Pot",
        price: 4099,
        desc: "Elevate your garden with our Hanging Flower Pot, a stylish and space-saving solution to showcase your favorite blooms. Crafted with durable materials and a modern design, these pots effortlessly suspend from any sturdy support, adding a touch of elegance to your indoor or outdoor space.",
    }, 
];
export const Sale = [
    {
        id: 0, 
        image: "https://myhomestore.pk/cdn/shop/products/il_1140xN.3646795440_nlyr_jpg.jpg?v=1672131560",
        title: "Gold Metal Wall Decor",
        price: 2599,
        desc: "Elevate your living space with our exquisite Gold Metal Wall Decor, a captivating blend of elegance and sophistication. Crafted with precision, this stunning piece seamlessly combines modern design with timeless allure, adding a touch of opulence to any room. ",
    }, 
    {
        id: 1, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSCu3gZQ9ZPmb2qHvU5qGZqH0qFDAuPOok8w&usqp=CAU",
        title: "Sofa Couch",
        price: 3099,
        desc: "Indulge in supreme comfort and style with our exquisite Sofa Couch. Crafted with precision and upholstered in luxurious fabrics, this contemporary piece seamlessly blends modern aesthetics with unparalleled relaxation. Elevate your living space with the perfect combination of sophistication and coziness.",
    }, 
    {
        id: 2, 
        image: "https://cdn1.bigcommerce.com/server600/eqcqd/products/34910/images/899011/BT-698-GY-GG_LS__61541.1657221582.1280.1280.jpg?c=2",
        title: "Low Back Gray Office Chair",
        price: 2599,
        desc: "Upgrade your office space with our Low Back Gray Office Chair, combining sleek design with ergonomic comfort. This stylish chair features a modern gray finish, perfect for any workspace, and provides optimal support for extended periods of seated work. ",
    }, 
    {
        id: 3, 
        image: "https://m.media-amazon.com/images/I/61FA8QXhJSL._AC_UF1000,1000_QL80_.jpg",
        title: "Soup Serving Bowls",
        price: 2099,
        desc: "Elevate your dining experience with our elegant Soup Serving Bowls. Crafted with durable and stylish materials, these bowls are perfect for presenting your favorite soups in a sophisticated manner. Enhance your table setting and enjoy cozy meals with our premium Soup Serving Bowls.",
    },
    {
        id: 4, 
        image: "https://m.media-amazon.com/images/I/51O9Tl-NarL._AC_UF894,1000_QL80_.jpg",
        title: "Dining Chairs Set",
        price: 8099,
        desc: "Elevate your dining experience with our exquisite Dining Chairs Set. Crafted with a perfect blend of comfort and style, these chairs feature premium materials and contemporary design, adding a touch of sophistication to your dining space. ",
    }, 
    {
        id: 5, 
        image: "https://cdn.renodepot.com/webassets/images/330741550_MainImage_001_l.jpg",
        title: "Console Table",
        price: 2099,
        desc: "Elevate your space with our exquisite Console Table, a perfect blend of style and functionality. Crafted with precision, this sleek and versatile piece seamlessly complements any decor, offering a chic solution for showcasing your favorite items. ",
    }, 
    {
        id: 6, 
        image: "https://urbangalleria.com/cdn/shop/products/5_64f3bec5-e664-4693-8dc8-4be3d49360f6_1024x1024.jpg?v=1610620212",
        title: "Woodall Roacking Chair",
        price: 7600,
        desc: "Experience the perfect blend of comfort and style with the Woodall Rocking Chair. Crafted from high-quality wood, this timeless piece adds a touch of elegance to any space. Whether you're enjoying a quiet evening or reading your favorite book, the Woodall Rocking Chair promises relaxation in classic charm.",
    },  
    {
        id: 7, 
        image: "https://m.media-amazon.com/images/I/61YFzRQWUJL.jpg",
        title: "Simple Procelian Planter",
        price: 2099,
        desc: "Elevate your greenery with our Simple Porcelain Planter, a minimalist yet stylish addition to any space. Crafted with precision and elegance, this sleek planter seamlessly complements your plants, bringing a touch of modern sophistication to your home or office decor. ",
    }, 
    {
        id: 8, 
        image: "https://assets.weimgs.com/weimgs/rk/images/wcm/products/202343/0103/anillo-handcrafted-ceramic-mug-q.jpg",
        title: "Ceramic Cups",
        price: 3599,
        desc: "Elevate your sipping experience with our exquisite Ceramic Cups. Crafted with precision and artistry, these durable cups not only enhance your beverage presentation but also offer a touch of sophistication to your daily rituals. Enjoy the perfect blend of style and functionality with our premium ceramic cups",
    }, 
    {
        id: 9, 
        image: "https://www.bareezehome.com.pk/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/f/c/fch-414a_b.jpg",
        title: "Linen Cushions",
        price: 1999,
        desc: "Elevate your home decor with our exquisite Linen Cushions, crafted for both comfort and style. Immerse yourself in the luxurious feel of high-quality linen fabric, adding a touch of sophistication to any space. Experience the perfect blend of chic design and cozy relaxation with our premium linen cushion ",
    }, 
    {
        id: 10, 
        image: "https://pth-homes.com/cdn/shop/collections/Shopify_category_banner_6.png?v=1686121710",
        title: "Throws Blankets",
        price: 9000,
        desc: "ndulge in cozy comfort with our luxurious Throws Blankets, crafted from premium materials for a soft and warm embrace. Elevate your home decor with a touch of elegance and warmth, making these blankets perfect for chilly evenings or stylish accents in any room.",
    }, 
    {
        id: 11, 
        image: "https://www.urbanplant.in/cdn/shop/files/Primary1copy_b778ed81-f3e1-449d-b723-8a52a4ac7b0d.webp?v=1685116236",
        title: "Hanging Planter",
        price: 2599,
        desc: "Elevate your greenery with our stylish Hanging Planter – a chic and space-saving solution to bring nature indoors. Crafted with durable materials and a modern design, this versatile planter effortlessly adds a touch of botanical charm to any room, turning your space into a thriving oasis. ",
    }, 

];

